### PR TITLE
Adds license texts for Apache2, BSD2 and BSD3 sourced from https://op…

### PR DESCRIPTION
**Pull request by ndejong**
Adds `data/license_template` texts for Apache2, BSD2 and BSD3 sourced from https://opensource.org/licenses

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Looks good, thanks!

**Comment by NiklasRosenstein** [comment]
Actually, one thought: Could you check what is the canonical short name of these licenses, and the way you would specify them in `setuptools.setup(license=...)` or in the `license` key in `package.yml`? If that doesn't match the filename exactly, I think we may want to do some conversion of the license name so it matches the filename.

**Comment by ndejong** [comment]
> Actually, one thought: Could you check what is the canonical short name of these licenses, and the way you would specify them in `setuptools.setup(license=...)` or in the `license` key in `package.yml`? If that doesn't match the filename exactly, I think we may want to do some conversion of the license name so it matches the filename.

Turns out, yes there are recognized short names for these software licenses published by the Linux Foundation -
https://spdx.org/licenses/

Also, the OSI also names the **SPDX short identifier** for each -
* `MIT` - https://opensource.org/licenses/MIT
* `BSD-2-Clause` - https://opensource.org/licenses/BSD-2-Clause
* `BSD-3-Clause` - https://opensource.org/licenses/BSD-3-Clause
* `Apache-2.0` - https://opensource.org/licenses/Apache-2.0

Checking Github for their [license definitions](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository) also lists identifiers that at-a-glance are the same as the SPDX, however they are lowercase.

Adding to the confusion, the OSI classifiers do not distinguish between things like BSD-2-Clause and BSD-3-Clause.  Then there are some commonly understood abbreviations such as those that I have used to name these license files in the first place.

An approach that uses `.lower()` with a lookup table makes it possible to manage these different situations and the rate at which the lookup table needs to be updated should be very low.

How do we support situations where the developer needs/wants to use a license that is not listed?  Does this warrant the introduction of a `license_file` attribute into `package.yml` that then allows the developer to do their own thing?

Will look at sorting this out later in the week.

**Comment by ndejong** [comment]
Commit implements a license-name template map to license filename

**Comment by NiklasRosenstein** [comment]
Hey @ndejong , I've created https://github.com/NiklasRosenstein/shut/pull/18 because this PR has a complicated set of conflicts.

> How do we support situations where the developer needs/wants to use a license that is not listed? Does this warrant the introduction of a license_file attribute into package.yml that then allows the developer to do their own thing?

I've made the license renderer log a warning in that case and simply not produce a license file. :)

**Pull request closed without merging**
